#!/usr/bin/env python
"""Generate a supplementary LaTeX table of the most constrained states.

Phase 6 §6.3 — Quota summary table for supplement.

Produces ``quota_summary_k_grid.csv`` and optionally a LaTeX snippet
``quota_most_constrained.tex`` showing the top-10 most constrained
groups and their quota allocations across the full k-grid.

Usage
-----
    python -m coreset_selection.scripts.quota_summary_table --output-dir supplement/tables
"""

from __future__ import annotations

import argparse
import csv
import os
from typing import Optional, Sequence

import numpy as np


def generate_quota_summary(
    output_dir: str = "supplement/tables",
    k_grid: Optional[Sequence[int]] = None,
    alpha_geo: float = 1.0,
    top_n: int = 10,
    data_dir: Optional[str] = None,
):
    """Generate quota summary CSV and LaTeX table.

    Parameters
    ----------
    output_dir : str
        Where to write output files.
    k_grid : sequence of int, optional
        Coreset sizes (defaults to manuscript K_GRID).
    alpha_geo : float
        Dirichlet smoothing parameter.
    top_n : int
        Number of most-constrained groups to highlight.
    data_dir : str, optional
        Data directory for real data; ``None`` → synthetic.
    """
    from ..scripts.print_quota import _build_geo_from_data
    from ..geo.projector import GeographicConstraintProjector
    from ..geo.kl import compute_quota_path

    if k_grid is None:
        from ..config.constants import K_GRID
        k_grid = list(K_GRID)

    geo = _build_geo_from_data(data_dir)
    projector = GeographicConstraintProjector(
        geo=geo, alpha_geo=alpha_geo, min_one_per_group=True,
    )

    k_grid = sorted(set(int(k) for k in k_grid))
    path = compute_quota_path(
        pi=geo.pi,
        group_sizes=geo.group_sizes,
        k_grid=k_grid,
        alpha_geo=alpha_geo,
        min_one_per_group=True,
    )

    # Build a {k: cstar} mapping
    cstar_map = {row["k"]: np.array(row["cstar"], dtype=int) for row in path}

    os.makedirs(output_dir, exist_ok=True)

    # ---- CSV: full quota_summary_k_grid.csv ----
    csv_path = os.path.join(output_dir, "quota_summary_k_grid.csv")
    fieldnames = ["group", "n_g", "pi_g"] + [f"cstar_k{k}" for k in k_grid]
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for g in range(geo.G):
            row = {
                "group": geo.groups[g],
                "n_g": int(geo.group_sizes[g]),
                "pi_g": round(float(geo.pi[g]), 6),
            }
            for k in k_grid:
                row[f"cstar_k{k}"] = int(cstar_map[k][g])
            writer.writerow(row)
    print(f"Saved {csv_path}")

    # ---- LaTeX: top-N most constrained at the largest k ----
    k_max = max(k_grid)
    mc = projector.most_constrained_groups(k_max, top_n=top_n)
    mc_names = {m["group"] for m in mc}

    tex_path = os.path.join(output_dir, "quota_most_constrained.tex")
    k_cols = " & ".join(f"$c^\\star({k})$" for k in k_grid)
    header = f"State & $n_g$ & $\\pi_g$ & {k_cols} & Util.\\% \\\\"

    lines = [
        "% Auto-generated by scripts/quota_summary_table.py (Phase 6 §6.3)",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{Top {top_n} most capacity-constrained states and their "
        f"quotas $c^\\star(k)$ across the manuscript grid $\\mathcal{{K}}$.}}",
        "\\label{tab:quota-most-constrained}",
        "\\small",
        "\\begin{tabular}{l r r " + " ".join(["r"] * len(k_grid)) + " r}",
        "\\toprule",
        header,
        "\\midrule",
    ]

    for m in mc:
        g_idx = geo.groups.index(m["group"])
        counts_str = " & ".join(str(int(cstar_map[k][g_idx])) for k in k_grid)
        util_str = f"{m['utilisation'] * 100:.1f}"
        lines.append(
            f"{m['group']} & {m['n_g']} & {m['pi_g']:.4f} & "
            f"{counts_str} & {util_str} \\\\"
        )

    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]

    with open(tex_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Saved {tex_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate quota summary table for supplement."
    )
    parser.add_argument(
        "--output-dir", type=str, default="supplement/tables",
        help="Output directory.",
    )
    parser.add_argument(
        "--top", type=int, default=10,
        help="Number of most-constrained groups.",
    )
    parser.add_argument(
        "--data-dir", type=str, default=None,
        help="Data directory (omit for synthetic).",
    )
    args = parser.parse_args()
    generate_quota_summary(
        output_dir=args.output_dir,
        top_n=args.top,
        data_dir=args.data_dir,
    )


if __name__ == "__main__":
    main()
